// Five Star Conveyancing — short, factual per-county context used to give
// each generated location page genuine, non-duplicated substance beyond
// swapping in a town name. Deliberately avoids numeric claims (average
// house prices, transaction volumes) that would need a verified dataset
// this project doesn't have — see CLAUDE.md's data-integrity rule.
export const COUNTY_BLURBS: Record<string, string> = {
  Bedfordshire: "sits within easy commuting distance of London, so a mix of established towns and newer developments both come up often in searches and enquiries.",
  Berkshire: "covers everything from riverside towns on the Thames to commuter hubs near the M4, which can mean a wider-than-usual range of lease lengths and service charge arrangements on flats.",
  Buckinghamshire: "spans market towns, Chiltern villages and the planned town of Milton Keynes, so the paperwork on a purchase can look quite different depending on which part of the county you're in.",
  Cambridgeshire: "mixes a historic university city with flat, agricultural fen country further out, and searches often need to account for both flood-risk and drainage-board considerations in the latter.",
  Cornwall: "has a large proportion of holiday-let and second-home property along its coastline, which can bring extra planning and use-class checks that don't come up in most inland purchases.",
  Cheshire: "has a strong commuter-belt character around Manchester and Liverpool alongside its own market towns, with a good number of newer estate developments that come with management company arrangements.",
  "County Durham": "runs from former coalfield towns to the cathedral city itself, and a number of ex-mining areas have historic mining searches worth checking as part of a purchase.",
  Cumbria: "takes in the Lake District alongside working towns on the coast, and National Park planning restrictions are worth checking early if a property sits within its boundary.",
  Derbyshire: "stretches from Peak District market towns to former industrial areas nearer Derby, with mining-search considerations relevant in several of the latter.",
  Devon: "covers both coastal resort towns and inland market towns, with second-home and holiday-let activity noticeably higher in some coastal areas than others.",
  Dorset: "combines Jurassic Coast resort towns with inland market towns, and coastal erosion or flood-risk searches are worth particular attention nearer the coastline.",
  "East Riding of Yorkshire": "spans Hull itself and a run of smaller market towns further into the Yorkshire Wolds, with flood-risk searches especially relevant near the Humber.",
  "East Sussex": "runs from Brighton's dense, largely leasehold housing stock to smaller Wealden market towns further inland, so the mix of freehold and leasehold varies a lot by area.",
  Essex: "takes in commuter towns close to London as well as coastal and rural areas further out, with new-build developments common enough that management company charges come up regularly.",
  Gloucestershire: "spans the Cotswolds' stone-built market towns and the city of Gloucester itself, and listed-building or conservation-area restrictions are worth checking in the older towns.",
  "Greater London": "is dominated by leasehold flats far more than most of the country, so lease length, ground rent and service charge checks tend to matter more here than elsewhere.",
  "Greater Manchester": "combines the city centre's high-rise leasehold developments with a ring of distinct towns that were once separate boroughs, each with their own character.",
  Hampshire: "covers everything from the naval city of Portsmouth to New Forest villages, where National Park and common-land considerations can affect a purchase.",
  Herefordshire: "is mostly rural market towns and villages near the Welsh border, with agricultural and listed-building searches coming up more often than in more urban counties.",
  Hertfordshire: "sits just north of London and has a strong commuter-town character, with a good number of new-build developments alongside its older market towns.",
  "Isle of Wight": "is an island, which means searches often need to account for coastal erosion and, in places, more limited local infrastructure than on the mainland.",
  Kent: "runs from Channel ports to commuter towns near London, and its coastal towns bring their own set of flood-risk and coastal-erosion considerations.",
  Lancashire: "spans old mill towns, the Fylde coast resorts and rural areas further out, with mining-search considerations relevant in several of the former.",
  Leicestershire: "mixes the city of Leicester with market towns and villages further out, generally with a more even split between freehold and leasehold than in bigger cities.",
  Lincolnshire: "is mostly flat, agricultural land dotted with market towns, where flood-risk and drainage searches are worth particular attention given the terrain.",
  Merseyside: "centres on Liverpool but includes distinct towns on both sides of the Mersey, each with their own mix of Victorian terraces and newer developments.",
  Norfolk: "covers the Broads, the coast and inland market towns, with flood-risk searches especially relevant near the Broads and the coastline.",
  "North Yorkshire": "is England's largest county, spanning the Yorkshire Dales, the North York Moors and market towns in between — National Park restrictions apply in a good part of it.",
  Northamptonshire: "sits centrally in England with a mix of shoe-industry heritage towns and newer commuter developments closer to the M1.",
  Northumberland: "is mostly rural, with market towns near Hadrian's Wall and the Scottish border, and National Park considerations relevant to properties within it.",
  Nottinghamshire: "mixes the city of Nottingham with former coalfield towns, where mining searches are a routine part of conveyancing in a number of areas.",
  Oxfordshire: "combines the university city with Cotswold-edge market towns, where listed-building and conservation-area restrictions come up often in the older centres.",
  Rutland: "is England's smallest historic county, with a small number of market towns and a generally rural, low-density property market.",
  Shropshire: "borders Wales and is largely rural, with market towns spaced well apart and agricultural considerations relevant to many purchases.",
  Somerset: "spans the Mendips, the Levels and coastal towns, with flood-risk searches especially relevant on the low-lying Somerset Levels.",
  "South Yorkshire": "centres on Sheffield but includes a number of former coalfield towns, where mining searches are a routine part of the process.",
  Staffordshire: "mixes the Potteries around Stoke-on-Trent with market towns further out, and mining-search considerations apply in several of the former.",
  Suffolk: "is mostly rural market towns and a stretch of coastline, with coastal erosion searches relevant to some seafront properties.",
  Surrey: "sits just south-west of London with a strong commuter character, and green-belt restrictions affect development in a good part of the county.",
  "Tyne and Wear": "centres on Newcastle and Sunderland, with a mix of Victorian terraces and newer riverside developments across both banks of the Tyne.",
  Warwickshire: "takes in Shakespeare country around Stratford-upon-Avon alongside more industrial towns nearer Coventry, with quite different property types across the county.",
  "West Midlands": "is England's most populous metropolitan county outside London, built around Birmingham, Coventry and Wolverhampton with the Black Country towns in between.",
  "West Sussex": "runs from South Downs market towns to the coast, and South Downs National Park restrictions apply to properties within its boundary.",
  "West Yorkshire": "centres on Leeds and Bradford but includes a large number of former mill towns in the Pennine valleys, each with their own distinct character.",
  Wiltshire: "spans Salisbury Plain, the Cotswolds' southern edge and market towns in between, with a mix of rural and MOD-adjacent land use worth checking in places.",
  Worcestershire: "combines the Malvern Hills with market towns along the Severn, generally a more rural property market than its West Midlands neighbours.",
  "Blaenau Gwent": "is a former coal and iron valleys area, where mining searches are a routine part of buying property in most of the county.",
  Bridgend: "sits between Cardiff and Swansea with a mix of coastal towns and former mining valleys, the latter carrying routine mining-search considerations.",
  Caerphilly: "spans former mining valleys just north of Cardiff, where mining searches are a standard part of the conveyancing process.",
  Carmarthenshire: "is Wales's largest county by area, mostly rural with a scattering of market towns along its river valleys.",
  Ceredigion: "is a mostly rural, coastal county in west Wales, centred on the university town of Aberystwyth.",
  Conwy: "spans the North Wales coast's resort towns and the mountains of Eryri (Snowdonia) further inland, with National Park restrictions applying in the latter.",
  Denbighshire: "covers North Wales coastal towns and the Clwydian Range further inland, with a mix of resort and market-town property types.",
  Flintshire: "sits closest to the English border of any Welsh county, with a mix of industrial towns near the Dee estuary and more rural areas further south.",
  Gwynedd: "takes in most of Eryri (Snowdonia) National Park alongside coastal towns on the Llŷn Peninsula, with National Park restrictions relevant to a large share of its area.",
  "Isle of Anglesey": "is an island county connected to the mainland by two bridges, with a generally rural and coastal property market.",
  "Merthyr Tydfil": "is a former iron and coal town at the head of the South Wales valleys, where mining searches are a routine part of buying here.",
  Monmouthshire: "sits along the Welsh side of the Wye Valley and border with England, mostly rural market towns rather than the valleys' industrial heritage further west.",
  "Neath Port Talbot": "combines industrial towns along the coast with valleys further inland, the latter carrying routine mining-search considerations.",
  Newport: "is a city and county borough on the Severn Estuary, with a mix of urban and semi-rural property across its boundary.",
  Pembrokeshire: "is largely coastal, with much of the county within the Pembrokeshire Coast National Park, where planning restrictions can apply.",
  Powys: "is Wales's largest county by area and its most rural, a scattering of small market towns across the Cambrian Mountains and Brecon Beacons.",
  "Rhondda Cynon Taf": "spans several former coal-mining valleys just north of Cardiff, where mining searches are a standard part of the conveyancing process.",
  Torfaen: "runs along the Afon Lwyd valley from Cwmbran to Blaenavon, with industrial heritage that carries routine mining-search considerations further north.",
  "Vale of Glamorgan": "is a mostly rural, coastal county bordering Cardiff, generally with less of the mining heritage found in the valleys further north.",
  Wrexham: "is North Wales's largest urban area outside the coast, with a mix of town-centre and semi-rural property across the county borough.",
};
